# Generated by Django 2.2.3 on 2020-10-02 11:13

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=profiles.models.upload_update_image),
        ),
    ]
